import { openUrl, sealUrl } from '@/lib/xtream-crypto';
import { relayHeaders, relayUrl } from '@/lib/xtream';

/**
 * Shared playback proxy logic.
 *
 * Used by both playback entry points:
 *  - /api/public/xtream-play?t=<token>      single opaque URL (channel, movie, segment)
 *  - /api/public/stream/<token>/<path...>   token = base URL, path appended
 *
 * The path-based form exists for DASH (`.mpd`) and for HLS manifests that use
 * `$Number$`-style templates: those URLs are generated by the player at runtime,
 * so they cannot be sealed one by one — sealing the *base* keeps the provider
 * URL and relay token hidden while the player appends whatever it needs.
 */

const SAFE_HEADERS = [
  'content-type',
  'content-range',
  'content-disposition',
  'last-modified',
  'etag',
];

const TRANSIENT = new Set([408, 429]);
const finalUrlCache = new Map<string, { url: string; expires: number }>();

export function isManifest(url: string, contentType: string | null): boolean {
  if (/\.m3u8(\?|$)/i.test(url)) return true;
  const ct = (contentType ?? '').toLowerCase();
  return ct.includes('mpegurl') || ct.includes('vnd.apple.mpegurl');
}

export function isDash(url: string, contentType: string | null): boolean {
  if (/\.mpd(\?|$)/i.test(url)) return true;
  return (contentType ?? '').toLowerCase().includes('dash+xml');
}

/** Fetch provider bytes through the configured relay only. */
async function fetchRelay(url: string, request: Request): Promise<Response> {
  const headers = new Headers(relayHeaders());
  headers.set('User-Agent', 'AndamTV/1.0');
  const range = request.headers.get('range');
  if (range) headers.set('Range', range);
  return fetch(relayUrl(url), { headers, redirect: 'follow' });
}

async function drain(res: Response) {
  try {
    await res.body?.cancel();
  } catch {
    /* nothing to drain */
  }
}

function isTransient(status: number): boolean {
  return TRANSIENT.has(status) || status >= 500;
}

export async function fetchUpstream(upstream: string, request: Request): Promise<Response> {
  let res = await fetchRelay(upstream, request);
  // Retry only genuine transient failures. A 401/403/411 response comes from
  // the provider and retrying it (or bypassing the relay) cannot repair it.
  if (!res.ok && isTransient(res.status)) {
    await drain(res);
    await new Promise((r) => setTimeout(r, 350));
    res = await fetchRelay(upstream, request);
  }
  return res;
}

export function clientStatus(status: number): number {
  // Preserve meaningful provider failures instead of turning every response
  // into a route-level 502, which the app shell treats as a server crash.
  if ([400, 401, 403, 404, 408, 410, 411, 429].includes(status)) return status;
  return 502;
}

/**
 * Some playlist entries look like a raw `.ts` stream but actually redirect to an
 * HLS manifest on a different host (`.../528.ts` → `http://host:8080/X/index.m3u8`).
 * The relay does not report the final URL, so relative URIs inside the manifest
 * would resolve against the wrong base. Follow the redirects ourselves to learn
 * the real base; if the provider refuses a direct call we keep the original URL.
 */
export async function resolveFinalUrl(upstream: string): Promise<string> {
  const cached = finalUrlCache.get(upstream);
  if (cached && cached.expires > Date.now()) return cached.url;
  let current = upstream;
  for (let i = 0; i < 5; i += 1) {
    let res: Response;
    try {
      res = await fetch(current, {
        redirect: 'manual',
        headers: { 'User-Agent': 'AndamTV/1.0', Accept: '*/*' },
      });
    } catch {
      finalUrlCache.set(upstream, { url: current, expires: Date.now() + 60_000 });
      return current;
    }
    await drain(res);
    const location = res.headers.get('location');
    if (res.status >= 300 && res.status < 400 && location) {
      try {
        current = new URL(location, current).toString();
        continue;
      } catch {
        break;
      }
    }
    break;
  }
  finalUrlCache.set(upstream, { url: current, expires: Date.now() + 60_000 });
  return current;
}

/**
 * Reads just the first playlist from the response. Live `.ts` endpoints that
 * answer with a manifest keep the connection open and repeat the playlist
 * forever, so `res.text()` never resolves and playback hangs.
 */
export async function readManifestText(res: Response): Promise<string> {
  const reader = res.body?.getReader();
  if (!reader) return res.text();
  const decoder = new TextDecoder();
  const startedAt = Date.now();
  let text = '';
  const cut = () => {
    const second = text.indexOf('#EXTM3U', 7);
    return second > 0 ? text.slice(0, second) : '';
  };
  while (text.length < 262_144 && Date.now() - startedAt < 8_000) {
    const chunk = await Promise.race([
      reader.read(),
      new Promise<{ done: true; value: undefined }>((resolve) =>
        setTimeout(() => resolve({ done: true, value: undefined }), 5_000),
      ),
    ]);
    if (chunk.done) break;
    text += decoder.decode(chunk.value, { stream: true });
    if (cut()) break;
  }
  try {
    await reader.cancel();
  } catch {
    /* already closed */
  }
  return cut() || text;
}

/** Reads an XML manifest with a size/time cap (MPDs are small). */
export async function readXmlText(res: Response): Promise<string> {
  const reader = res.body?.getReader();
  if (!reader) return res.text();
  const decoder = new TextDecoder();
  const startedAt = Date.now();
  let text = '';
  while (text.length < 2_000_000 && Date.now() - startedAt < 8_000) {
    const chunk = await Promise.race([
      reader.read(),
      new Promise<{ done: true; value: undefined }>((resolve) =>
        setTimeout(() => resolve({ done: true, value: undefined }), 5_000),
      ),
    ]);
    if (chunk.done) break;
    text += decoder.decode(chunk.value, { stream: true });
    if (text.includes('</MPD>')) break;
  }
  try {
    await reader.cancel();
  } catch {
    /* already closed */
  }
  return text;
}

/** `/api/public/stream/<sealed base>/` — anything the player appends is relayed. */
async function proxyBase(absolute: string): Promise<string> {
  const dir = absolute.replace(/[^/]*$/, '');
  return `/api/public/stream/${encodeURIComponent(await sealUrl(dir))}/`;
}

/**
 * Rewrites manifest URIs to *relative* playback URLs. Absolute URLs built from
 * the incoming request origin are wrong behind the preview/published proxy
 * (the server sees http://localhost:8080), which made the browser request a
 * dead origin and left the player spinning forever.
 */
export async function rewriteManifest(text: string, upstream: string): Promise<string> {
  const base = new URL(upstream);
  const absolute = (ref: string) => new URL(ref, base).toString();
  const token = async (ref: string) =>
    `/api/public/xtream-play?t=${encodeURIComponent(await sealUrl(absolute(ref)))}`;

  const lines = text.split(/\r?\n/);
  const out: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      out.push(line);
      continue;
    }
    if (trimmed.startsWith('#')) {
      // Rewrite URI="..." attributes (keys, media, i-frame playlists).
      const uriMatch = trimmed.match(/URI="([^"]+)"/);
      if (uriMatch && uriMatch[1]) {
        out.push(trimmed.replace(/URI="([^"]+)"/, `URI="${await token(uriMatch[1])}"`));
      } else {
        out.push(line);
      }
      continue;
    }
    out.push(await token(trimmed));
  }
  return out.join('\n');
}

/**
 * Rewrites a DASH manifest so every segment is fetched through the relay.
 *
 * Segment URLs in DASH are built at runtime from `$Number$` / `$Time$`
 * templates, so they cannot be sealed individually like HLS lines. Instead the
 * manifest gets a `<BaseURL>` that points at the path-based proxy: the player
 * appends its generated filename and the server resolves it against the sealed
 * provider base.
 */
export async function rewriteMpd(text: string, upstream: string): Promise<string> {
  const base = new URL(upstream);
  const absolutise = (ref: string) => new URL(ref, base).toString();
  let out = text;

  // <Location> points straight at the provider; dash.js would use it for the
  // live manifest refresh and hit CORS. Drop it so refreshes stay on the proxy.
  out = out.replace(/<Location>[\s\S]*?<\/Location>/gi, '');


  // Absolute template URLs: seal the directory, keep the filename template.
  const attrRe = /(media|initialization|sourceURL|initializationSegmentURL)="(https?:[^"]+)"/gi;
  const attrJobs: Array<[string, string]> = [];
  for (const m of out.matchAll(attrRe)) attrJobs.push([m[0] as string, m[2] as string]);
  for (const [full, value] of attrJobs) {
    const attr = full.slice(0, full.indexOf('='));
    const replacement = `${attr}="${(await proxyBase(value)) + value.replace(/^.*\//, '')}"`;
    out = out.split(full).join(replacement);
  }

  // Existing <BaseURL> elements → proxied equivalents.
  const baseJobs: Array<[string, string]> = [];
  for (const m of out.matchAll(/<BaseURL[^>]*>([\s\S]*?)<\/BaseURL>/gi)) {
    baseJobs.push([m[0] as string, (m[1] as string).trim()]);
  }
  let hasBaseUrl = false;
  for (const [full, value] of baseJobs) {
    if (!value) continue;
    hasBaseUrl = true;
    const abs = absolutise(value.endsWith('/') ? value : `${value}/`);
    out = out.split(full).join(`<BaseURL>${await proxyBase(`${abs}x`)}</BaseURL>`);
  }

  // No BaseURL at all: inject one before the first <Period> (schema order).
  if (!hasBaseUrl) {
    const proxied = `<BaseURL>${await proxyBase(base.toString())}</BaseURL>`;
    const idx = out.search(/<Period[\s>]/i);
    out = idx > 0 ? out.slice(0, idx) + proxied + out.slice(idx) : out.replace(/(<MPD[^>]*>)/i, `$1${proxied}`);
  }
  return out;
}

/** Copies only headers that are safe to expose, normalising Content-Range. */
export function safeHeaders(res: Response, request: Request): Headers {
  const headers = new Headers();
  for (const key of SAFE_HEADERS) {
    const value = res.headers.get(key);
    if (value) headers.set(key, value);
  }
  // Some providers answer a suffix range (`bytes=-N`, which browsers use to
  // find the moov atom of non-faststart MP4s) with a malformed
  // `Content-Range: bytes -N/total`. Chrome/Safari reject that and the
  // movie/episode never starts, so normalise it into a real byte range.
  const cr = headers.get('content-range');
  if (cr && !/^bytes \d+-\d+\/\d+$/.test(cr.trim())) {
    const total = Number((cr.match(/\/(\d+)\s*$/) ?? [])[1] ?? NaN);
    const req = (request.headers.get('range') ?? '').match(/bytes=(\d*)-(\d*)/);
    if (Number.isFinite(total) && req) {
      const suffix = !req[1] && req[2] ? Number(req[2]) : NaN;
      const start = Number.isFinite(suffix) ? Math.max(0, total - suffix) : Number(req[1] || 0);
      const end = Number.isFinite(suffix) ? total - 1 : Number(req[2] || total - 1);
      headers.set('Content-Range', `bytes ${start}-${end}/${total}`);
    } else {
      headers.delete('Content-Range');
    }
  }
  headers.set('Cache-Control', 'no-store');
  headers.set('Access-Control-Allow-Origin', '*');
  return headers;
}

export function errorResponse(status: number): Response {
  return new Response(
    status === 404 ? 'Stream not found' : `Stream unavailable (provider ${status})`,
    {
      status: clientStatus(status),
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Cache-Control': 'no-store',
        'Content-Type': 'text/plain; charset=utf-8',
      },
    },
  );
}

/** Shared body: relay `upstream`, rewriting HLS/DASH manifests on the way out. */
export async function proxyStream(upstream: string, request: Request): Promise<Response> {
  let res: Response;
  try {
    res = await fetchUpstream(upstream, request);
  } catch (err) {
    console.error('[stream-proxy] relay error', err);
    return new Response('Stream unavailable', { status: 502 });
  }

  if (!res.ok) {
    console.error('[stream-proxy] relay responded', res.status, res.statusText);
    return errorResponse(res.status);
  }

  const contentType = res.headers.get('content-type');
  const headers = safeHeaders(res, request);

  if (isDash(upstream, contentType)) {
    const text = await readXmlText(res);
    const finalUrl =
      res.headers.get('x-final-url') ||
      (/\.mpd(\?|$)/i.test(upstream) ? upstream : await resolveFinalUrl(upstream));
    headers.set('Content-Type', 'application/dash+xml');
    return new Response(await rewriteMpd(text, finalUrl), { status: 200, headers });
  }

  if (isManifest(upstream, contentType)) {
    const text = await readManifestText(res);
    // The relay may follow redirects without reporting where it landed, so
    // resolve the real base ourselves before rewriting relative URIs.
    const finalUrl =
      res.headers.get('x-final-url') ||
      (/\.m3u8(\?|$)/i.test(upstream) ? upstream : await resolveFinalUrl(upstream));
    headers.set('Content-Type', 'application/vnd.apple.mpegurl');
    return new Response(await rewriteManifest(text, finalUrl), { status: 200, headers });
  }

  headers.set('Accept-Ranges', 'bytes');
  return new Response(res.body, { status: res.status, headers });
}

/** Resolves a sealed-base token plus the player-appended path into a real URL. */
export async function resolveBasePath(token: string, path: string): Promise<string | null> {
  const base = await openUrl(token);
  if (!base) return null;
  try {
    return new URL(path, base).toString();
  } catch {
    return null;
  }
}
