/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicTmdbDiscoverRouteImport } from './routes/api/public/tmdb-discover'
import { Route as ApiPublicXtreamRouteImport } from './routes/api/public/xtream'
import { Route as ApiPublicXtreamPlayRouteImport } from './routes/api/public/xtream-play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmdbDiscoverRoute = ApiPublicTmdbDiscoverRouteImport.update({
  id: '/api/public/tmdb-discover',
  path: '/api/public/tmdb-discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXtreamRoute = ApiPublicXtreamRouteImport.update({
  id: '/api/public/xtream',
  path: '/api/public/xtream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXtreamPlayRoute = ApiPublicXtreamPlayRouteImport.update({
  id: '/api/public/xtream-play',
  path: '/api/public/xtream-play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/tmdb-discover'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/public/tmdb-discover'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/tmdb-discover'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicTmdbDiscoverRoute: typeof ApiPublicTmdbDiscoverRoute
  ApiPublicXtreamRoute: typeof ApiPublicXtreamRoute
  ApiPublicXtreamPlayRoute: typeof ApiPublicXtreamPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmdb-discover': {
      id: '/api/public/tmdb-discover'
      path: '/api/public/tmdb-discover'
      fullPath: '/api/public/tmdb-discover'
      preLoaderRoute: typeof ApiPublicTmdbDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xtream': {
      id: '/api/public/xtream'
      path: '/api/public/xtream'
      fullPath: '/api/public/xtream'
      preLoaderRoute: typeof ApiPublicXtreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xtream-play': {
      id: '/api/public/xtream-play'
      path: '/api/public/xtream-play'
      fullPath: '/api/public/xtream-play'
      preLoaderRoute: typeof ApiPublicXtreamPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicTmdbDiscoverRoute: ApiPublicTmdbDiscoverRoute,
  ApiPublicXtreamRoute: ApiPublicXtreamRoute,
  ApiPublicXtreamPlayRoute: ApiPublicXtreamPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
