/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin/providers'
import { Route as ApiPublicTmdbDiscoverRouteImport } from './routes/api/public/tmdb-discover'
import { Route as ApiPublicXtreamRouteImport } from './routes/api/public/xtream'
import { Route as ApiPublicXtreamPlayRouteImport } from './routes/api/public/xtream-play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicTmdbDiscoverRoute = ApiPublicTmdbDiscoverRouteImport.update({
  id: '/api/public/tmdb-discover',
  path: '/api/public/tmdb-discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXtreamRoute = ApiPublicXtreamRouteImport.update({
  id: '/api/public/xtream',
  path: '/api/public/xtream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXtreamPlayRoute = ApiPublicXtreamPlayRouteImport.update({
  id: '/api/public/xtream-play',
  path: '/api/public/xtream-play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/providers'
    | '/api/public/tmdb-discover'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/providers'
    | '/api/public/tmdb-discover'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/providers'
    | '/api/public/tmdb-discover'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTmdbDiscoverRoute: typeof ApiPublicTmdbDiscoverRoute
  ApiPublicXtreamRoute: typeof ApiPublicXtreamRoute
  ApiPublicXtreamPlayRoute: typeof ApiPublicXtreamPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/tmdb-discover': {
      id: '/api/public/tmdb-discover'
      path: '/api/public/tmdb-discover'
      fullPath: '/api/public/tmdb-discover'
      preLoaderRoute: typeof ApiPublicTmdbDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xtream': {
      id: '/api/public/xtream'
      path: '/api/public/xtream'
      fullPath: '/api/public/xtream'
      preLoaderRoute: typeof ApiPublicXtreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xtream-play': {
      id: '/api/public/xtream-play'
      path: '/api/public/xtream-play'
      fullPath: '/api/public/xtream-play'
      preLoaderRoute: typeof ApiPublicXtreamPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTmdbDiscoverRoute: ApiPublicTmdbDiscoverRoute,
  ApiPublicXtreamRoute: ApiPublicXtreamRoute,
  ApiPublicXtreamPlayRoute: ApiPublicXtreamPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
